"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { totpCodeSchema, type AdminMfaSetupDTO } from "@wovenwhale/backend/contracts";
import { CircleAlert } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import type { z } from "zod";
import { Button } from "@/components/ui/Button";
import { Checkbox, TextField } from "@/components/ui/Field";
import { api } from "@/lib/api/client";
import { errorMessage } from "@/lib/api/errors";
import styles from "./MfaSetup.module.css";
import { RecoveryCodes } from "./RecoveryCodes";

/**
 * Enrolment: show a QR code and key, confirm with a first code, then show
 * recovery codes. 2FA is only switched on after the code is confirmed.
 */
export function MfaSetup({ email, next }: { email: string; next: string }) {
  const router = useRouter();
  const [setup, setSetup] = useState<AdminMfaSetupDTO | null>(null);
  const [codes, setCodes] = useState<string[] | null>(null);
  const [saved, setSaved] = useState(false);
  const [alert, setAlert] = useState<string | null>(null);
  const [starting, setStarting] = useState(false);
  const form = useForm<z.input<typeof totpCodeSchema>, unknown, z.output<typeof totpCodeSchema>>({
    resolver: zodResolver(totpCodeSchema),
    defaultValues: { code: "" },
  });

  const start = async () => {
    setAlert(null);
    setStarting(true);
    try {
      setSetup(await api<AdminMfaSetupDTO>("/admin/auth/2fa/setup", { method: "POST" }));
    } catch (error) {
      setAlert(errorMessage(error));
    } finally {
      setStarting(false);
    }
  };

  const confirm = form.handleSubmit(async ({ code }) => {
    setAlert(null);
    try {
      const { recoveryCodes } = await api<{ recoveryCodes: string[] }>("/admin/auth/2fa/enable", { method: "POST", body: { code } });
      setCodes(recoveryCodes);
    } catch (error) {
      form.resetField("code");
      setAlert(errorMessage(error));
    }
  });

  const errorBanner = alert && (
    <div className={styles.alert} role="alert">
      <CircleAlert size={18} aria-hidden="true" />
      <p>{alert}</p>
    </div>
  );

  if (codes) {
    return (
      <div className={styles.flow}>
        <p className={styles.done} role="status">
          Two-factor authentication is on.
        </p>
        <RecoveryCodes codes={codes} email={email} />
        <Checkbox label="I've saved my recovery codes" checked={saved} onChange={(e) => setSaved(e.target.checked)} />
        <Button
          size="lg"
          fullWidth
          disabled={!saved}
          onClick={() => {
            router.replace(next);
            router.refresh();
          }}
        >
          Continue
        </Button>
      </div>
    );
  }

  if (!setup) {
    return (
      <div className={styles.flow}>
        {errorBanner}
        <p className={styles.text}>
          You&apos;ll need an authenticator app on your phone, such as Google Authenticator, Microsoft Authenticator, 1Password or Authy.
        </p>
        <Button size="lg" fullWidth loading={starting} onClick={start}>
          Start setup
        </Button>
      </div>
    );
  }

  return (
    <form className={styles.flow} onSubmit={confirm} noValidate>
      {errorBanner}
      <ol className={styles.steps}>
        <li>
          <p>Scan this QR code with your authenticator app.</p>
          {/* A data URL generated by the API; next/image adds nothing here. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img className={styles.qr} src={setup.qrDataUrl} alt="QR code for your authenticator app" width={200} height={200} />
          <details className={styles.manual}>
            <summary>Can&apos;t scan it? Enter the key instead</summary>
            <code className={styles.secret} data-testid="totp-secret">
              {setup.secret.match(/.{1,4}/g)?.join(" ")}
            </code>
          </details>
        </li>
        <li>
          <TextField
            label="Enter the 6-digit code it shows"
            inputMode="numeric"
            autoComplete="one-time-code"
            maxLength={6}
            error={form.formState.errors.code?.message}
            {...form.register("code")}
          />
        </li>
      </ol>
      <Button type="submit" size="lg" fullWidth loading={form.formState.isSubmitting}>
        Turn on two-factor
      </Button>
    </form>
  );
}
